FROM alpine:latest

RUN apk --no-cache add dnsmasq bash

#COPY  /etc/dnsmasq/dnsmasq.conf \
#     && dnsmasq.d /etc/dnsmasq.d

RUN rm -rf /etc/dnsmasq.conf

EXPOSE 53/tcp 53/udp

CMD ["dnsmasq", "-k"]
